#!/usr/bin/env python3
"""Regenerate the parts of each skill that are shared between all six.

Two blocks are identical, or near-identical, in every skill:

  * `references/figma-export.md` - the Email Love plugin guidance, which is one
    shared body plus a per-platform section.
  * the "Handling untrusted content" / "Escaping and dynamic evaluation" section
    in `SKILL.md`, which differs only in which dynamic-evaluation mechanism the
    platform exposes.

Each `.skill` archive still has to be self-contained, so the shared text is
copied into every skill rather than referenced. This script is what keeps the
copies honest. `--check` fails instead of writing, and CI runs it that way so a
hand-edit to one copy cannot drift away from the others unnoticed.
"""
import argparse, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = sorted(p.name for p in (ROOT / "skills").iterdir() if (p / "SKILL.md").exists())

SEC_START = "<!-- shared:security:start - generated by scripts/sync_shared.py, do not edit here -->"
SEC_END = "<!-- shared:security:end -->"


def figma(slug: str) -> str:
    d = ROOT / "shared" / "figma"
    tail = (d / "_tail.md").read_text().replace(
        "{{EXPORT_SOURCE}}", (d / f"{slug}.source").read_text())
    return (d / "_head.md").read_text() + (d / f"{slug}.md").read_text() + "\n" + tail


def security(slug: str) -> str:
    d = ROOT / "shared" / "security"
    mechanisms = json.loads((d / "mechanisms.json").read_text())
    escaping = json.loads((d / "escaping.json").read_text())
    body = (d / "_body.md").read_text() \
        .replace("{{MECHANISM}}", mechanisms[slug]) \
        .replace("{{ESCAPING}}", escaping[slug])
    return f"{SEC_START}\n\n{body.rstrip()}\n\n{SEC_END}\n"


def splice(text: str, block: str) -> str:
    """Replace the marked section, or insert it before '## Output style'."""
    if SEC_START in text:
        head, rest = text.split(SEC_START, 1)
        _, tail = rest.split(SEC_END, 1)
        return head + block.rstrip("\n") + tail
    anchor = "## Output style"
    i = text.index(anchor)
    return text[:i] + block + "\n---\n\n" + text[i:]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if any generated file is out of date")
    args = ap.parse_args()

    stale = []
    for slug in SKILLS:
        targets = {
            ROOT / "skills" / slug / "references" / "figma-export.md": figma(slug),
            ROOT / "skills" / slug / "SKILL.md":
                splice((ROOT / "skills" / slug / "SKILL.md").read_text(), security(slug)),
        }
        for path, want in targets.items():
            have = path.read_text() if path.exists() else None
            if have == want:
                continue
            if args.check:
                stale.append(path.relative_to(ROOT))
            else:
                path.write_text(want)
                print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        print("Shared blocks are out of date:", file=sys.stderr)
        for p in stale:
            print(f"  {p}", file=sys.stderr)
        print("\nRun: python3 scripts/sync_shared.py", file=sys.stderr)
        return 1
    print("shared blocks in sync" if args.check else "done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
