#!/usr/bin/env python3
"""Regenerate the Claude plugin folders in plugins/ from skills/ and the marketplace.

Claude Code installs a bare skill folder as a plugin. The Claude apps (Cowork,
the desktop app, claude.ai) do not: they sync a marketplace server-side and
refuse a plugin folder without `.claude-plugin/plugin.json` and its skills at
`skills/<name>/SKILL.md`. With every entry pointing at a bare skill folder,
"Add marketplace" failed there with nothing more than "Marketplace sync failed".
So each marketplace entry points at a folder this script writes:

    plugins/<name>/.claude-plugin/plugin.json   from the entry in .claude-plugin/marketplace.json
    plugins/<name>/skills/<name>/               the files the .skill archive ships, unchanged

`skills/<name>/` stays the only place to edit a skill, and the marketplace entry
the only place to edit its plugin metadata. `--check` fails instead of writing,
and CI runs it that way, so a copy cannot drift from its source unnoticed.

    python3 scripts/sync_plugins.py
    python3 scripts/sync_plugins.py --check
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLUGINS = ROOT / "plugins"

# The same allowlist scripts/build.sh packs into a .skill archive, so a plugin
# install and an uploaded .skill carry the same files. scripts/verify_dist.sh
# compares the two after every build.
SHIPPED_DIRS = ("references", "agents", "evals", "assets")
SHIPPED_SUFFIXES = {".md", ".yaml", ".json", ".png", ".svg", ".jpg", ".webp"}

# Marketplace entry fields that are also plugin.json fields, in output order.
MANIFEST_FIELDS = ("name", "displayName", "version", "description", "author",
                   "homepage", "repository", "license", "keywords")

README = """\
# Claude plugin folders

Generated by `scripts/sync_plugins.py`. Do not edit anything in this folder.

The Claude apps (Cowork, the desktop app and claude.ai) install a plugin only from
a folder that holds `.claude-plugin/plugin.json` and its skills at
`skills/<name>/SKILL.md`. Each folder here wraps one skill that way, and
`.claude-plugin/marketplace.json` points at it. Claude Code installs the same
folders.

- To change a skill, edit `skills/<name>/`.
- To change a plugin's description, display name or version, edit its entry in
  `.claude-plugin/marketplace.json`.

Then run `python3 scripts/sync_plugins.py`. CI runs it with `--check` and fails
when this folder has drifted from those sources.
"""


def expected() -> dict[pathlib.Path, bytes]:
    """Every file plugins/ should hold, mapped to its exact bytes."""
    manifest = json.loads(
        (ROOT / ".claude-plugin" / "marketplace.json").read_text(encoding="utf-8"))
    licence = (ROOT / "LICENSE").read_bytes()

    want = {PLUGINS / "README.md": README.encode()}
    for entry in manifest.get("plugins", []):
        name = entry.get("name")
        skill = ROOT / "skills" / str(name)
        if not (skill / "SKILL.md").is_file():
            raise SystemExit(f"marketplace entry `{name}` has no skills/{name}/SKILL.md")

        plugin = PLUGINS / name
        meta = {key: entry[key] for key in MANIFEST_FIELDS if key in entry}
        want[plugin / ".claude-plugin" / "plugin.json"] = \
            (json.dumps(meta, indent=2, ensure_ascii=False) + "\n").encode()

        dest = plugin / "skills" / name
        want[dest / "SKILL.md"] = (skill / "SKILL.md").read_bytes()
        want[dest / "LICENSE"] = licence
        for sub in SHIPPED_DIRS:
            for path in sorted((skill / sub).rglob("*")):
                if path.is_file() and path.suffix in SHIPPED_SUFFIXES:
                    want[dest / path.relative_to(skill)] = path.read_bytes()
    return want


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if anything in plugins/ is out of date")
    args = ap.parse_args()

    want = expected()
    have = {p for p in PLUGINS.rglob("*") if p.is_file() or p.is_symlink()} \
        if PLUGINS.exists() else set()

    stale = []
    for path, data in sorted(want.items()):
        if path.is_file() and not path.is_symlink() and path.read_bytes() == data:
            continue
        stale.append(path)
        if not args.check:
            if path.is_symlink():
                path.unlink()
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(f"wrote {path.relative_to(ROOT)}")

    for path in sorted(have - set(want)):
        stale.append(path)
        if not args.check:
            path.unlink()
            print(f"removed {path.relative_to(ROOT)}")

    if not args.check and PLUGINS.exists():
        # Deepest first, so a folder emptied by the removals above goes too.
        for folder in sorted((p for p in PLUGINS.rglob("*") if p.is_dir()),
                             key=lambda p: len(p.parts), reverse=True):
            if not any(folder.iterdir()):
                folder.rmdir()

    if args.check and stale:
        print("Plugin folders are out of date:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
        print("\nRun: python3 scripts/sync_plugins.py", file=sys.stderr)
        return 1
    print("plugin folders in sync" if args.check else "done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
